// This file is automatically generated by Clarigen.
// Don't make changes to this file, or they'll
// be overwritten.
import { factory } from "https://deno.land/x/clarigen@v0.4.15/mod.ts";
import { simnet } from "./../artifacts/clarigen.ts";

export const { test, contracts, accounts } = factory(simnet);

export const {
  bnsV1,
  executorDao,
  extensionTrait,
  nameRegistry,
  nameWrapper,
  nftTrait,
  proposalBootstrap,
  proposalTrait,
  testUtils,
  wrapperMigrator,
} = contracts;
