
// This file is automatically generated by Clarigen.
// Don't make changes to this file, or they'll
// be overwritten.
import { factory } from "https://deno.land/x/clarigen@v0.4.12/mod.ts";
import { simnet } from "./../artifacts/clarigen.ts";

export const { test, contracts, accounts } = factory(simnet);

export const {
  bnsV1,
  executorDao,
  extensionTrait,
  managedNamespaces,
  nameRegistry,
  nameWrapper,
  nftTrait,
  onchainResolver,
  proposalBootstrap,
  proposalTrait,
  testUtils,
  wrapperMigrator
} = contracts;
