[project]
name = 'bns'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.bns-v1]
path = 'contracts/bns-v1.clar'
clarity_version = 1
epoch = 2.0

[contracts.demo-controller]
path = 'contracts/demo-controller.clar'
clarity_version = 1
epoch = 2.0

[contracts.bnsx-extensions]
path = 'contracts/bnsx-extensions.clar'
clarity_version = 1
epoch = 2.0

[contracts.extension-trait]
path = 'contracts/traits/extension-trait.clar'
clarity_version = 1
epoch = 2.0

[contracts.bnsx-registry]
path = 'contracts/core/name-registry.clar'
clarity_version = 1
epoch = 2.0

[contracts.name-wrapper]
path = 'contracts/name-wrapper.clar'
clarity_version = 1
epoch = 2.0

[contracts.nft-trait]
path = 'contracts/traits/nft-trait.clar'
clarity_version = 1
epoch = 2.0

[contracts.proposal-bootstrap]
path = 'contracts/proposals/proposal-bootstrap.clar'
clarity_version = 1
epoch = 2.0

[contracts.proposal-2]
path = 'contracts/proposals/proposal-2.clar'
clarity_version = 1
epoch = 2.0

[contracts.proposal-trait]
path = 'contracts/traits/proposal-trait.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-utils]
path = 'contracts/test-utils.clar'
clarity_version = 1
epoch = 2.0

# [contracts.test-utils-2-1]
# path = 'contracts/test-utils-2-1.clar'
# clarity_version = 2
# epoch = 2.1

# [contracts.wrapper-migrator]
# path = 'contracts/wrapper-migrator.clar'
# clarity_version = 2
# epoch = 2.1

[contracts.wrapper-migrator]
path = 'contracts/wrapper-migrator-v1.clar'
clarity_version = 1
epoch = 2.0

[contracts.query-helper]
path = 'contracts/query-helper.clar'
clarity_version = 1
epoch = 2.0

# [contracts.onchain-resolver]
# path = "contracts/onchain-resolver.clar"
# clarity_version = 2
# epoch = 2.1

# [contracts.bns-init]
# path = 'contracts/testnet/bns-init.clar'
# clarity_version = 1
# epoch = 2.0

# [contracts.fake-registry]
# path = "contracts/fake-registry.clar"
# clarity_version = 1
# epoch = 2.0

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = true
trusted_caller = true
callee_filter = true
